<a href="https://colab.research.google.com/github/HiraSadiq2/Datascience_Repo/blob/main/DataScience_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/DS_project_data/france accidents/Characteristics.csv", encoding="latin-1")

<ipython-input-3-9aa72acdd5df>:1: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/content/drive/MyDrive/DS_project_data/france accidents/Characteristics.csv", encoding="latin-1")

In [ ]:
# syntax of renaming the coloumn
 #dataframe.rename(columns = {'jisko':'jiske sath'}, inplace = True)
# df.rename(columns={'an':'Year_of_Acc'}, inplace=True)
# df.rename(columns={'mois':'Month_of_Acc'}, inplace=True)
# df.rename(columns={'jour':'Day_of_Acc'}, inplace=True)
# df.rename(columns={'hrmn':'Time_of_Acc_hhmm'}, inplace=True)
# df.rename(columns={'lum':'Lightning_condition'}, inplace=True)
# df.rename(columns={'int':'Type_of_Intersection'}, inplace=True)
# df.rename(columns={'atm':'Atmospheric_Conditions'}, inplace=True)
# df.rename(columns={'col':'Type_of_Collision'}, inplace=True)
# df.rename(columns={'adr':'Postal_Address'}, inplace=True)
# df.rename(columns={'com':'Municipality'}, inplace=True)
# df.rename(columns={'dep':'Department'}, inplace=True)
# df.rename(columns={'gps':'GPS'}, inplace=True)

df.head()

,Num_Acc,Yr_of_Acc,Month_of_Acc,Day_of_Acc,Time_of_Acc_hhmm,Lightning_condition,agg,Type_of_Intersection,Atmospheric_Conditions,Type_of_Collision,Municipality,Postal_Address,GPS,lat,long,Department
0,201600000001,16,2,1,1445,1,2,1,8.0,3.0,5.0,"46, rue Sonneville",M,0.0,0.0,590
1,201600000002,16,3,16,1800,1,2,6,1.0,6.0,5.0,1a rue du cimetière,M,0.0,0.0,590
2,201600000003,16,7,13,1900,1,1,1,1.0,6.0,11.0,NaN,M,0.0,0.0,590
3,201600000004,16,8,15,1930,2,2,1,7.0,3.0,477.0,52 rue victor hugo,M,0.0,0.0,590
4,201600000005,16,12,23,1100,1,2,3,1.0,3.0,11.0,rue Joliot curie,M,0.0,0.0,590

In [ ]:
places=pd.read_csv("/content/drive/MyDrive/DS_project_data/france accidents/places.csv", encoding="latin-1")
places.head()

<ipython-input-6-16bb8b47e03c>:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  places=pd.read_csv("/content/drive/MyDrive/DS_project_data/france accidents/places.csv", encoding="latin-1")

,Num_Acc,catr,voie,v1,v2,circ,nbv,pr,pr1,vosp,prof,plan,lartpc,larrout,surf,infra,situ,env1
0,201600000001,3.0,39,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,3.0,0.0,0.0,1.0,0.0,1.0,0.0
1,201600000002,3.0,39,NaN,NaN,1.0,0.0,NaN,NaN,0.0,1.0,2.0,0.0,58.0,1.0,0.0,1.0,0.0
2,201600000003,3.0,1,NaN,NaN,2.0,2.0,NaN,NaN,0.0,1.0,3.0,0.0,68.0,2.0,0.0,3.0,99.0
3,201600000004,4.0,0,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,99.0
4,201600000005,4.0,0,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0

NI_route_num : Numeric Index of the route number \\
LAn_iof_road : Letter alphanumeric number of the road

In [ ]:
# places.rename(columns={'Num_Acc':'Accident_ID'}, inplace=True)
# places.rename(columns={'catr':'Category_of_Road'}, inplace=True)
# places.rename(columns={'voie':'Road_Number'}, inplace=True)
# places.rename(columns={'v1':'NI_route_num'}, inplace=True)
# places.rename(columns={'v2':'LAn_iof_road'}, inplace=True)
# places.rename(columns={'circ':'Traffic_regime'}, inplace=True)
# places.rename(columns={'nbv':'numof_traffic_lanes'}, inplace=True)
# places.rename(columns={'vosp':'Reserved_Lane'}, inplace=True)
# places.rename(columns={'prof':'Longitudinal Profile'}, inplace=True)
# places.rename(columns={'pr':'Home_pr_num'}, inplace=True)
# places.rename(columns={'pr1':'Distance_to_PR'}, inplace=True)
# places.rename(columns={'plan':'Drawing_in_Plan'}, inplace=True)
# places.rename(columns={'lartpc':'Central_Solid_Land'}, inplace=True)
# places.rename(columns={'larrout':'Width_assigned_to_vehicle'}, inplace=True)
# places.rename(columns={'surf':'Surface_Condition'}, inplace=True)
# places.rename(columns={'infra':'Development-Infrastructure'}, inplace=True)
# places.rename(columns={'situ':'Situation_of_Accident'}, inplace=True)
# places.rename(columns={'env1':'School_point'}, inplace=True)

In [ ]:
places.head()

,Accident_ID,Category_of_Road,Road_Number,NI_route_num,LAn_iof_road,Traffic_regime,numof_traffic_lanes,Home_pr_num,Distance_to_PR,Reserved_Lane,Longitudinal Profile,Drawing_in_Plan,Central_Solid_Land,Width_assigned_to_vehicle,Surface_Condition,Development-Infrastructure,Situation_of_Accident,School_point
0,201600000001,3.0,39,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,3.0,0.0,0.0,1.0,0.0,1.0,0.0
1,201600000002,3.0,39,NaN,NaN,1.0,0.0,NaN,NaN,0.0,1.0,2.0,0.0,58.0,1.0,0.0,1.0,0.0
2,201600000003,3.0,1,NaN,NaN,2.0,2.0,NaN,NaN,0.0,1.0,3.0,0.0,68.0,2.0,0.0,3.0,99.0
3,201600000004,4.0,0,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,99.0
4,201600000005,4.0,0,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0

In [ ]:
vehicles = pd.read_csv('/content/drive/MyDrive/DS_project_data/france accidents/vehicles.csv')
vehicles.head()

        Num_Acc  senc  catv  occutc  obs  obsm  choc  manv num_veh
0  201600000001   0.0     7       0  0.0   0.0   1.0   1.0     B02
1  201600000001   0.0     2       0  0.0   0.0   7.0  15.0     A01
2  201600000002   0.0     7       0  6.0   0.0   1.0   1.0     A01
3  201600000003   0.0     7       0  0.0   1.0   6.0   1.0     A01
4  201600000004   0.0    32       0  0.0   0.0   1.0   1.0     B02